apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
        - name: streamlit-container
          image: <ECR_REGISTRY>/streamlit-app:latest
          ports:
            - containerPort: 8501
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"